version: '3.8'

services:
  node:
      build: .
      ports:
        - "3300:3300"
      volumes:
        - .:/usr/src/app
      networks:
        - public

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - public

networks:
  public:
      external: true

